### ISSUE TITLE
Add network in the url

### ISSUE THREAD

**Issue by jolestar** [rooch-network/roochscan-frontend#5]
https://roochscan-frontend.vercel.app/tx/$tx_hash 

-> 

https://roochscan-frontend.vercel.app/main/tx/$tx_hash
https://roochscan-frontend.vercel.app/test/tx/$tx_hash
https://roochscan-frontend.vercel.app/dev/tx/$tx_hash
https://roochscan-frontend.vercel.app/local/tx/$tx_hash

**Comment by 0xfynnix** [comment]
also add network to account/object/transactions
